In [2]:
import numpy as np

In [3]:
# Создаем матрицу 2*3
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Создаем нулевую матрицу 2*2. Указываем сколько должно столбцов и строк должно быть 
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [32]:
# Создаем матрицу 3*3 c единицами на диагонали
t =  np.eye(3)
t

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
A = np.array([[1,2], [4,5]])
B = np.array([[-2,3], [0,1]])

In [11]:
# @ используется для матричного умножения
A@B

array([[-2,  5],
       [-8, 17]])

In [ ]:
#AB не равно BA. Так нельзя

In [12]:
B@A

array([[10, 11],
       [ 4,  5]])

In [13]:
# Умножение матриц можно записать через функцию dot
np.dot(A,B)

array([[-2,  5],
       [-8, 17]])

In [21]:
# Обратная матрица 
I = np.linalg.inv(A)
I
# I матрица обртано к А
#linlag - библиотека лин алгебры
#inv - inverse

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [22]:
#I матрица обртано к А. Проверим это утверждение. При умножении должна получится единичная матрица
I@A

array([[1., 0.],
       [0., 1.]])

In [23]:
A@I

array([[1., 0.],
       [0., 1.]])

In [25]:
C = np.array([[1,2],[2,4]]) #попробуем найти для этой матрицы обратную матрицу. Будет ошибка. У матрици С нет обратной матрицы
C

array([[1, 2],
       [2, 4]])

In [27]:
D = np.linalg.inv(C)


LinAlgError: Singular matrix